{
 "title": "my_dash Copy",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "node ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu usage by %",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - avg by (node) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[5m]))) * 100"
      }
     ]
    },
    {
     "title": "pods runnig on node",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_info{job=\"kube-state-metrics\", node=~\"$node\"}) by (node)\n"
      }
     ]
    },
    {
     "title": "Pod runnig ratio",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Running\"}) / sum(kube_pod_status_phase)*100"
      }
     ]
    }
   ]
  },
  {
   "title": "name space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "pod restats in name space ",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}) by (namespace)\n"
      }
     ]
    },
    {
     "title": "cpu usage by name sapce",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 7, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])) by (namespace)\n  / \n  8\n) * 100\n"
      }
     ]
    },
    {
     "title": "pod per name sapce",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_info{namespace=~\"$namespace\"}) by (namespace)"
      }
     ]
    },
    {
     "title": "Deployment per name sapce ",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_deployment_created{namespace=~\"$namespace\"}) by (namespace)\n"
      }
     ]
    },
    {
     "title": "Network I/O receive/transmit by Namespace ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\"}[5m])) by (namespace)",
       "legendFormat": "receive"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\"}[5m])) by (namespace)\n",
       "legendFormat": "transmit"
      }
     ]
    },
    {
     "title": "Disk I/O Read/Writes by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\"}[5m])) by (namespace)\n",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\"}[5m])) by (namespace)",
       "legendFormat": "writes"
      }
     ]
    },
    {
     "title": "Memory Usage by Namespace",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\"}) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Received for pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "receive"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "transmit"
      }
     ]
    },
    {
     "title": "Disk I/O read/write for pod ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Average Memory Usage per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(avg_over_time(container_memory_usage_bytes{pod=~\"$pod\", container!=\"\", container!=\"POD\"}[5m])) by (pod)\n"
      }
     ]
    },
    {
     "title": "Pod Age",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - kube_pod_created{pod=~\"$pod\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu usage by container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m])) by (container)\n\n"
      }
     ]
    },
    {
     "title": "memory usage byets by contianer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (container)"
      }
     ]
    }
   ]
  }
 ]
}